default: all

CFLAGS := -I./../../include  -Wall -I./include -I./src/minIni 
CC := g++

BINARIES := test
all : $(BINARIES)

LIBS := -lrt -lstdc++ -lach 

$(BINARIES): src/test.o
	$(CC) -o $@ $< $(LIBS)

%.o: %.cpp
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(BINARIES) src/*.o

