#!/bin/bash

SCREEN_SERVER=darwin-ach-server
SCREEN_CLIENT=darwin-ach-client

Kill()
{
  case "$1" in
	'server' )
		darwin-lofaro darwin-ach-walking off
		darwin-lofaro darwin-ach-server off
		darwin-lofaro ach-clear
	;;

  	'client' )
		darwin-lofaro darwin-ach-walking off
		darwin-lofaro ach-kill
		darwin-lofaro ach-clear
	;;

	'all' )
		darwin-lofaro darwin-ach-walking off
		darwin-lofaro darwin-ach-server off
		darwin-lofaro ach-kill
		darwin-lofaro ach-clear
	;;

	* )
		ShowUsage
	;;
  esac
}


Power()
{
  case "$1" in
	'on' )
		On
	;;

  	'off' )
		Off
	;;

	* )
		ShowUsage
	;;
  esac
}

Start()
{

  rm /tmp/darwin-ach-server.sh
  rm /tmp/darwin-ach-client.sh

  echo 'darwin-lofaro ach-reset'            >> /tmp/darwin-ach-server.sh
  echo 'darwin-lofaro darwin-ach-server on' >> /tmp/darwin-ach-server.sh
  echo 'darwin-lofaro ach-reset'            >> /tmp/darwin-ach-client.sh
  echo 'darwin-lofaro ach-remote'           >> /tmp/darwin-ach-client.sh

  chmod +x /tmp/darwin-ach-server.sh
  chmod +x /tmp/darwin-ach-client.sh

  case "$1" in
	'walking' )
	        echo '--- Starting Darwin-ach Walking ---'
		darwin-lofaro darwin-ach-walking on
	;;

	'server' )
	        echo '--- Starting Darwin-ach Server using Darwin Lofaro Legacy ---'
  		darwin-lofaro ach-reset
		darwin-lofaro darwin-ach-server on

#		/tmp/darwin-ach-server.sh
#		if ! screen -list | grep -q "$SCREEN_SERVER"; then
#                	echo '--- Starting Darwin-Ach Server using Darwin Lofaro Legacy ---'
#                	screen -d -m -S $SCREEN_SERVER /bin/bash -c /tmp/darwin-ach-server.sh
#			sleep 2
#			On
#        	else
#                	echo '--- Darwin-Ach Server usign Darwin Lofaro Legacy already running ---'
#        	fi
	;;

  	'client' )
	        echo '--- Starting Darwin-ach Client using Darwin Lofaro Legacy ---'
  		darwin-lofaro ach-reset
  		darwin-lofaro ach-remote

#		/tmp/darwin-ach-client.sh
#		if ! screen -list | grep -q "$SCREEN_CLIENT"; then
#                	echo '--- Starting Darwin-Ach Client using Darwin Lofaro Legacy ---'
#                	screen -d -m -S $SCREEN_CLIENT /bin/bash -c /tmp/darwin-ach-client.sh
#        	else
#                	echo '--- Darwin-Ach Client usign Darwin Lofaro Legacy already running ---'
#        	fi
#		darwin-lofaro ach-reset
#		darwin-lofaro ach-remote
	;;

	'local' )
	        echo '--- Starting Darwin-ach Server (local) using Darwin Lofaro Legacy ---'
  		darwin-lofaro ach-reset
		darwin-lofaro darwin-ach-server on

#		/tmp/darwin-ach-server.sh
#		if ! screen -list | grep -q "$SCREEN_SERVER"; then
#                	echo '--- Starting Darwin-Ach Server using Darwin Lofaro Legacy ---'
#                	screen -d -m -S $SCREEN_SERVER /bin/bash -c $CMD_SERVER
#        	else
#                	echo '--- Darwin-Ach Server usign Darwin Lofaro Legacy already running ---'
#        	fi
	;;

	* )
		ShowUsage
	;;
  esac
}

Stop()
{

  case "$1" in
	'walking' )
	        echo '--- Stopping Darwin-ach Walking ---'
		darwin-lofaro darwin-ach-walking off
	;;

	'server' )
	        echo '--- Stopping Darwin-ach Server using Darwin Lofaro Legacy ---'
		darwin-lofaro darwin-ach-walking off
		Off
		darwin-lofaro darwin-ach-server off
		darwin-lofaro ach-clear
#        	screen -S "$SCREEN_SERVER" -X quit > /dev/null
#      		if ! screen -list | grep -q "$SCREEN_SERVER"; then
#                	echo '--- Darwin-ach Server using Darwin Lofaro Legacy Stopped ---'
#        	else
#                	echo '--- Darwin-ach Server using Darwin Lofaro Legacy Failed to Stop ---'
#        	fi
	;;

  	'client' )
	        echo '--- Stopping Darwin-ach Client using Darwin Lofaro Legacy ---'
		darwin-lofaro darwin-ach-walking off
		darwin-lofaro ach-kill
		darwin-lofaro ach-clear
#        	screen -S "$SCREEN_CLIENT" -X quit > /dev/null
#      		if ! screen -list | grep -q "$SCREEN_CLIENT"; then
#                	echo '--- Darwin-ach Client using Darwin Lofaro Legacy Stopped ---'
#        	else
#                	echo '--- Darwin-ach Client using Darwin Lofaro Legacy Failed to Stop ---'
#        	fi
	;;

	'local' )
		echo '--- Stopping Darwin-ach Server/Client (local) using Darwin Lofaro Legacy ---'
		darwin-lofaro darwin-ach-walking off
		Off
		darwin-lofaro darwin-ach-server off
		darwin-lofaro ach-clear
#        	screen -S "$SCREEN_SERVER" -X quit > /dev/null
#      		if ! screen -list | grep -q "$SCREEN_SERVER"; then
#			echo '--- Darwin-ach Server/Client (local) using Darwin Lofaro Legacy Stopped ---'
#        	else
#			echo '--- Darwin-ach Server/Client (local) using Darwin Lofaro Legacy Failed to Stop ---'
#        	fi
	;;
	* )
		ShowUsage
	;;
  esac
}

On()
{
  darwin-lofaro darwin-ach-power on
}

Off()
{
  darwin-lofaro darwin-ach-power off
}



ShowUsage()
{
        echo 
        echo '================================================='
        echo '================================================='
        echo '======  Darwin-Ach for Darin Lofaro Legacy ======'
        echo '============   for the Darwin OP    ============='
        echo '================================================='
        echo '=============== Daniel M. Lofaro ================'
        echo '=============== dan@danlofaro.com ==============='
        echo '================================================='
        echo '================================================='
        echo ''
        echo 'start                                            '
        echo '-  server     : Starts the server (darwin) side  '
	echo '                and turns power on               '
	echo '-  client     : Starts the client (external side)'
	echo '-  local      : Starts server and client on the  '
	echo '                same machine and turns poer on   '
	echo '-  walking    : Starts the waking process        '
        echo ''
        echo 'stop                                             '
        echo '-  server     : Stops the server (darwin) side   '
	echo '                and turns power off              '
	echo '-  client     : Stops the client (external side) '
	echo '-  local      : Stops server and client on the   '
	echo '                same machine and turns power off '
	echo '-  walking    : Stops the walking process        '
	echo ''
	echo 'power                                            '
        echo '-  on         : Turns power on                   '
	echo '-  off        : Turns power off                  '
	echo ''
	echo 'kill             	                               '
	echo '-  server     : Kills server and ach channels    '
	echo '-  client     : Kills client, ach channels, and  '
	echo '                achd remote connection           '
	echo '-  all        : Kills the client and server      '
	echo ''
}


case "$1" in 
	'start' )
		Start $2 $3
	;;

	'stop' )
		Stop $2
	;;

	'power' )
		Power $2
	;;

	'kill' )
		Kill $2
	;;	

	* )
		ShowUsage
		exit 1
	;;	
esac	
exit 0
