#!/bin/bash
HUMBLE_INSTALL_DIR=~/ros2_humble/
DEB_VERSION=$(env -i bash -c '. /etc/os-release; echo $VERSION_CODENAME')
PACKAGE_NAME=darwin-legacy
INSTALL_DIR=/etc/$PACKAGE_NAME
INCLUDE_DIR=/usr/include/$PACKAGE_NAME
ROS_BUILD_FILE=do_build.sh
ROS_RUN_FILE=run_darwin_lofaro.sh
ROS_CLOCK_RUN_FILE=run_darwin_clock_lofaro.sh

DARWIN_CLOCK_SCREEN_NAME=darwin-lofaro-clock
DARWIN_SCREEN_NAME=darwin-lofaro

DARWIN_ACH_CHAN_REF='darwin-ach-chan-ref'
DARWIN_ACH_CHAN_REF_WALKING='darwin-ach-chan-ref-walking'
DARWIN_ACH_CHAN_STATE='darwin-ach-chan-state'
DARWIN_ACH_CHAN_CMD='darwin-ach-chan-cmd'
DARWIN_ACH_CHAN_CMD_RETURN='darwin-ach-chan-ret'

DARWIN_IP='10.5.0.249'
#DARWIN_IP='10.111.111.11'

KillAch()
{
  sudo kill -9 $(pidof achd)
  rm /dev/shm/achshm-darwin*
}

MakeAch()
{
#  ach -1 -C $DARWIN_ACH_CHAN_REF -m 10 -n 3000
#  ach -1 -C $DARWIN_ACH_CHAN_STATE -m 10 -n 3000
#  ach -1 -C $DARWIN_ACH_CHAN_CMD -m 10 -n 3000
#  ach -1 -C $DARWIN_ACH_CHAN_CMD_RETURN -m 10 -n 3000
  ach -1 mk $DARWIN_ACH_CHAN_REF -m 10 -n 3000
  ach -1 mk $DARWIN_ACH_CHAN_REF_WALKING -m 10 -n 3000
  ach -1 mk $DARWIN_ACH_CHAN_STATE -m 10 -n 3000
  ach -1 mk $DARWIN_ACH_CHAN_CMD -m 10 -n 3000
  ach -1 mk $DARWIN_ACH_CHAN_CMD_RETURN -m 10 -n 3000
  chmod 777 /dev/shm/achshm-darwin*
}

AchRemote()
{
  MakeAch
  achd -r push $1 $DARWIN_ACH_CHAN_REF &
  achd -r pull $1 $DARWIN_ACH_CHAN_STATE &
  achd -r push $1 $DARWIN_ACH_CHAN_CMD &
  achd -r pull $1 $DARWIN_ACH_CHAN_CMD_RETURN &
}


LowLatency()
{
	setserial /dev/ttyUSB0 low_latency
#	sudo setserial /dev/ttyUSB0 low_latency
	sync
#	sudo sync
	sleep 1
	echo '---- Low Latency Set ----'
}
StatusId()
{
	if ! screen -list | grep -q "$DARWIN_SCREEN_NAME"; then
		echo 1
	else 
		echo 0
	fi
}

Status()
{
	if ! screen -list | grep -q "$DARWIN_SCREEN_NAME"; then
		echo '--- Darwin Lofaro Legacy STOPED ---'
		exit 1
	else 
		echo '--- Darwin Lofaro Legacy RUNNING ---'
		exit 0
	fi
}

Start()
{
  DarwinLegacyRos2Start
  DarwinLegacyClockRos2Start
}

Stop()
{
  DarwinLegacyClockRos2Stop
  DarwinLegacyRos2Stop
}

DarwinLegacyRos2Stop()
{
	echo '--- Stopping Darwin Lofaro Legacy ---'
	screen -S "$DARWIN_SCREEN_NAME" -X quit > /dev/null
	if ! screen -list | grep -q "$DARWIN_SCREEN_NAME"; then
		echo '--- Darwin Lofaro Legacy Stopped ---'
	else 
		echo '--- Darwin Lofaro Legacy Failed to Stop ---'
	fi
}


DarwinLegacyRos2Start()
{
	cd $INSTALL_DIR/ros2
#	if ! screen -list | grep -q $DARWIN_SCREEN_NAME; then
	if ! screen -list | grep -q "$DARWIN_SCREEN_NAME"; then
		echo '--- Starting Darwin Lofaro Legacy ---'
		screen -d -m -S $DARWIN_SCREEN_NAME /bin/bash -c ./$ROS_RUN_FILE
	else 
		echo '--- Darwin Lofaro Legacy already running ---'
	fi
}

DarwinLegacyClockRos2Start()
{
	cd $INSTALL_DIR/ros2
#	if ! screen -list | grep -q $DARWIN_CLOCK_SCREEN_NAME; then
	if ! screen -list | grep -q "$DARWIN_CLOCK_SCREEN_NAME"; then
		echo '--- Starting Darwin Lofaro Legacy Clock ---'
		screen -d -m -S $DARWIN_CLOCK_SCREEN_NAME /bin/bash -c ./$ROS_CLOCK_RUN_FILE
	else 
		echo '--- Darwin Lofaro Legacy Clock already running ---'
	fi
}
DarwinLegacyClockRos2Stop()
{
	echo '--- Stopping Darwin Lofaro Legacy Clock ---'
	screen -S "$DARWIN_CLOCK_SCREEN_NAME" -X quit > /dev/null
	if ! screen -list | grep -q "$DARWIN_CLOCK_SCREEN_NAME"; then
		echo '--- Darwin Lofaro Legacy Clock Stopped ---'
	else 
		echo '--- Darwin Lofaro Legacy Clock Failed to Stop ---'
	fi
}

DarwinLegacy()
{
	THE_DIR=$(pwd)
	sudo rm -rf $INSTALL_DIR
	sudo mkdir -p $INSTALL_DIR
	echo $INSTALL_DIR
        sudo cp -r ../include/ $INSTALL_DIR/
        sudo cp -r ../ros2/ $INSTALL_DIR/
#	sudo mkdir /etc/rc.local.d
#	chmod +x darwin-legacy.sh
#	sudo cp darwin-legacy.sh /etc/rc.local.d/
#	echo $INCLUDE_DIR
#	sudo rm $INCLUDE_DIR
#        sudo ln -s $INSTALL_DIR/include $INCLUDE_DIR

}

ShowUsage()
{
	echo 
	echo '================================================='
	echo '================================================='
	echo '============  Darwin Lofaro Legacy  ============='
	echo '============   for the Darwin OP    ============='
	echo '================================================='
	echo '=============== Daniel M. Lofaro ================'
	echo '=============== dan@danlofaro.com ==============='
	echo '================================================='
	echo '================================================='
	echo ''
	echo 'start         : Starts the Darwin Lofaro Legacy  '
	echo '                system and clock                 '
	echo ''
	echo 'stop          : Stops the Darwin Lofaro Legacy   '
	echo '                system and clock                 '
	echo ''
	echo 'status        : Checks to see if the system is   '
	echo '                running: Human readable          '
	echo ''
	echo 'status-id     : Checks to see if the system is   '
	echo '                running: 0 = running, 1 = stoped '
	echo ''
	echo 'low-latency   : sets serial to low latency mode  '
	echo ''
	echo 'start-daemon  : Starts the Darwin Lofaro Legacy  '
	echo '                system                           '
	echo ''
	echo 'start-clock   : Starts the Darwin Lofaro Legacy  '
	echo '                clock                            '
	echo ''
	echo 'stop-daemon   : Stops the Darwin Lofaro Legacy   '
	echo '                system                           '
	echo ''
	echo 'stop-clock    : Stops the Darwin Lofaro Legacy   '
	echo '                clock                            '
	echo ''
	echo 'ach-make      : Make ach channels                '
	echo ''
	echo 'ach-remote    : Start the remote ach daemon      '
	echo ''
	echo 'ach-kill      : stops remote connections and     '
	echo '                removes all ach channels         '
	echo ''
	echo
}


case "$1" in
	'status' )
		Status $@
	;;
	
	'status-id' )
		StatusId $@
	;;
	
        'low-latency' )
		LowLatency $@
	;;
	'start' )
		Start $@
	;;
	'start-daemon' )
		DarwinLegacyRos2Start $@
	;;
	'start-clock' )
		DarwinLegacyClockRos2Start $@
	;;
	'stop' )
		Stop $@
	;;
	'stop-daemon' )
		DarwinLegacyRos2Stop $@
	;;
	'stop-clock' )
		DarwinLegacyClockRos2Stop $@
	;;
	
	'ach-make' )
		MakeAch $@
	;;

	'ach-remote' )
		AchRemote $DARWIN_IP
	;;

	'ach-kill' )
		KillAch
	;;
	
	* )
		ShowUsage
		exit 1
esac

exit 0



